import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from app.models.booking import Booking

class NumberedCanvas(canvas.Canvas):
    """Custom canvas that adds a bold diagonal DEMO watermark on each page."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_watermark()
            self.draw_footer(num_pages)
            super().showPage()
        super().save()

    def draw_watermark(self):
        self.saveState()
        self.setFont("Helvetica-Bold", 42)
        # Light semi-transparent red/gray watermark
        self.setFillColor(colors.Color(0.85, 0.2, 0.1, alpha=0.12))
        self.translate(300, 420)
        self.rotate(45)
        self.drawCentredString(0, 0, "DEMO — NOT VALID FOR TRAVEL")
        self.drawCentredString(0, -60, "SIMULATION ONLY")
        self.restoreState()

    def draw_footer(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#526277"))
        footer_text = f"RailVoya (railvoya.co.in) • Independent Travel Redesign • Page {self._pageNumber} of {page_count}"
        self.drawCentredString(300, 25, footer_text)
        self.restoreState()


class PdfService:
    @staticmethod
    def generate_ticket_pdf(booking: Booking) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=40,
        )

        styles = getSampleStyleSheet()
        primary_navy = colors.HexColor("#102A43")
        action_orange = colors.HexColor("#C2410C")
        text_dark = colors.HexColor("#132238")
        text_muted = colors.HexColor("#526277")
        border_color = colors.HexColor("#DCE3ED")
        alert_red = colors.HexColor("#B42318")
        alert_bg = colors.HexColor("#FEF3F2")

        # Custom paragraph styles
        brand_title_style = ParagraphStyle(
            "BrandTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=primary_navy,
        )

        banner_style = ParagraphStyle(
            "BannerText",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            textColor=alert_red,
            alignment=1,  # Center
        )

        section_heading = ParagraphStyle(
            "SectionHeading",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=primary_navy,
            spaceAfter=6,
        )

        body_style = ParagraphStyle(
            "BodyDark",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=text_dark,
        )

        body_bold = ParagraphStyle(
            "BodyBold",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=text_dark,
        )

        elements = []

        # 1. Top Warning Banner
        banner_data = [[
            Paragraph("<b>NOTICE: DEMO TICKET — NOT VALID FOR TRAVEL ON INDIAN RAILWAYS</b><br/>This document is an electronic demonstration generated by RailVoya. No real reservation was created.", banner_style)
        ]]
        banner_table = Table(banner_data, colWidths=[540])
        banner_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), alert_bg),
            ("BOX", (0, 0), (-1, -1), 1.5, alert_red),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ]))
        elements.append(banner_table)
        elements.append(Spacer(1, 14))

        # 2. Header with Brand & PNR
        header_data = [
            [
                Paragraph("<b>Rail<font color='#C2410C'>Voya</font></b><br/><font size=8 color='#526277'>Every journey, made simpler. • railvoya.co.in</font>", brand_title_style),
                Paragraph(f"<font color='#526277'>PNR NUMBER</font><br/><b><font size=16 color='#102A43'>{booking.pnr_number}</font></b><br/><font size=8 color='#16734B'><b>● DEMO BOOKING {booking.status}</b></font>", ParagraphStyle("PnrHeader", alignment=2, leading=16))
            ]
        ]
        header_table = Table(header_data, colWidths=[320, 220])
        header_table.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(header_table)
        elements.append(Spacer(1, 12))
        elements.append(HRFlowable(width="100%", thickness=1, color=border_color, spaceAfter=14))

        # 3. Journey Details Grid
        elements.append(Paragraph("Journey Information", section_heading))
        journey_data = [
            [
                Paragraph("<font color='#526277'>Train Number & Name</font>", body_style),
                Paragraph(f"<b>{booking.train_number} / {booking.train_name}</b>", body_bold),
                Paragraph("<font color='#526277'>Date of Journey</font>", body_style),
                Paragraph(f"<b>{booking.journey_date.strftime('%a, %d %b %Y')}</b>", body_bold),
            ],
            [
                Paragraph("<font color='#526277'>From Station</font>", body_style),
                Paragraph(f"<b>{booking.origin_code} ({booking.departure_time})</b>", body_bold),
                Paragraph("<font color='#526277'>To Station</font>", body_style),
                Paragraph(f"<b>{booking.destination_code} ({booking.arrival_time} {'+' + str(booking.arrival_day_offset) if booking.arrival_day_offset else ''})</b>", body_bold),
            ],
            [
                Paragraph("<font color='#526277'>Class & Quota</font>", body_style),
                Paragraph(f"<b>{booking.travel_class} • {booking.quota} Quota</b>", body_bold),
                Paragraph("<font color='#526277'>Boarding Station</font>", body_style),
                Paragraph(f"<b>{booking.boarding_station_code}</b>", body_bold),
            ],
            [
                Paragraph("<font color='#526277'>Booking Reference</font>", body_style),
                Paragraph(f"<b>{booking.id[:18]}...</b>", body_style),
                Paragraph("<font color='#526277'>Booked At</font>", body_style),
                Paragraph(f"{booking.created_at.strftime('%d %b %Y, %H:%M UTC')}", body_style),
            ]
        ]
        journey_table = Table(journey_data, colWidths=[130, 140, 130, 140])
        journey_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ("BOX", (0, 0), (-1, -1), 1, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(journey_table)
        elements.append(Spacer(1, 14))

        # 4. Passenger Details Table
        elements.append(Paragraph("Passenger Details", section_heading))
        pax_rows = [
            [
                Paragraph("<b>#</b>", body_bold),
                Paragraph("<b>Passenger Name</b>", body_bold),
                Paragraph("<b>Age / Gender</b>", body_bold),
                Paragraph("<b>Berth Preference</b>", body_bold),
                Paragraph("<b>Booking Status</b>", body_bold),
                Paragraph("<b>Coach & Berth</b>", body_bold),
            ]
        ]
        for idx, p in enumerate(booking.passengers):
            pax_rows.append([
                Paragraph(str(idx + 1), body_style),
                Paragraph(f"<b>{p.full_name}</b>", body_style),
                Paragraph(f"{p.age} Yrs / {p.gender}", body_style),
                Paragraph(p.berth_preference, body_style),
                Paragraph(f"<font color='#16734B'><b>{p.current_status}</b></font>", body_style),
                Paragraph(f"<b>{p.assigned_coach} - {p.assigned_berth}</b> ({p.assigned_berth_type})", body_style),
            ])

        pax_table = Table(pax_rows, colWidths=[25, 160, 90, 95, 75, 95])
        pax_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ("BOX", (0, 0), (-1, -1), 1, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(pax_table)
        elements.append(Spacer(1, 14))

        # 5. Itemized Fare Breakdown & Contact
        elements.append(Paragraph("Payment & Fare Receipt", section_heading))
        fare_rows = [
            [Paragraph("Base Ticket Fare", body_style), Paragraph(f"Rs. {booking.base_fare:.2f}", body_style)],
            [Paragraph("Reservation & Superfast Surcharge", body_style), Paragraph(f"Rs. {booking.reservation_charge + booking.superfast_charge:.2f}", body_style)],
        ]
        if booking.tatkal_charge > 0:
            fare_rows.append([Paragraph("Tatkal Surcharge", body_style), Paragraph(f"Rs. {booking.tatkal_charge:.2f}", body_style)])
        if booking.gst_amount > 0:
            fare_rows.append([Paragraph("Goods & Services Tax (GST 5%)", body_style), Paragraph(f"Rs. {booking.gst_amount:.2f}", body_style)])

        fare_rows.append([
            Paragraph("<b>Total Amount Paid (Demo)</b>", body_bold),
            Paragraph(f"<b><font size=11 color='#102A43'>Rs. {booking.total_amount:.2f}</font></b>", body_bold)
        ])

        fare_table = Table(fare_rows, colWidths=[380, 160])
        fare_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -2), colors.HexColor("#F8FAFC")),
            ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#E2E8F0")),
            ("BOX", (0, 0), (-1, -1), 1, border_color),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(fare_table)
        elements.append(Spacer(1, 14))

        # 6. Legal & Independent Disclosure Box
        disclaimer_text = (
            "<b>IMPORTANT TRAVEL INSTRUCTIONS:</b><br/>"
            "1. <b>Honest Demo Mode:</b> This ticket was generated for software demonstration purposes on RailVoya (railvoya.co.in). It does NOT entitle passengers to board any train.<br/>"
            "2. <b>Independent Platform:</b> RailVoya is an independent design concept and is not affiliated with the Ministry of Railways, Government of India, or IRCTC.<br/>"
            "3. <b>Identification:</b> For real train travel, valid government-issued photo ID (Aadhaar, Passport, Driving License, Voter ID) is mandatory.<br/>"
            "4. <b>Berth Allocation:</b> Berth preferences are requests only. Final coach/berth allocation is decided by PRS charting algorithms."
        )
        disc_table = Table([[Paragraph(disclaimer_text, ParagraphStyle("Disc", parent=styles["Normal"], fontName="Helvetica", fontSize=7.5, leading=11, textColor=text_muted))]], colWidths=[540])
        disc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 0.5, border_color),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(disc_table)

        doc.build(elements, canvasmaker=NumberedCanvas)
        return buffer.getvalue()
